routes/web.php
<?php

use App\Models\Familly;
use App\Models\Student;
use App\Models\Contributor;
use App\Models\Minorstudent;
use App\Models\CourseSession;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AppelController;
use App\Http\Controllers\SchoolController;
use App\Http\Controllers\FamillyController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SubjectController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ContributorController;
use App\Http\Controllers\CourseSessionController;
use App\Http\Controllers\SessionStudentController;
use App\Http\Controllers\SessionRegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified', 'role'])->get('/register', [RegisterController::class, 'showRegister'])->name('showregister');

Route::middleware(['auth:sanctum', 'verified', 'role'])->post('/applyregister', [RegisterController::class, 'register'])->name('register');


Route::get('/', function () {
    return redirect(route('dashboard'));
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', [Controller::class, 'home'])->name('dashboard');

Route::middleware(['auth:sanctum', 'verified', 'role'])->get('/student', [StudentController::class, 'show'])->name('student');

Route::middleware(['auth:sanctum', 'verified'])->get('/student/new', [StudentController::class, 'new_major'])->name('newstudent');

Route::middleware(['auth:sanctum', 'verified'])->post('/student/add', [StudentController::class, 'add_major'])->name('addstudent');

Route::middleware(['auth:sanctum', 'verified'])->get('/student/del/{id}', [StudentController::class, 'del'])->name('delstudent');

Route::middleware(['auth:sanctum', 'verified'])->get('/student/csv', [StudentController::class, 'csvliststudent'])->name('csvstudentlist');

Route::middleware(['auth:sanctum', 'verified'])->get('/minorstudent/csv', [FamillyController::class, 'csvlistminorstudent'])->name('csvminorstudentlist');

Route::middleware(['auth:sanctum', 'verified'])->post('/student/mod', [StudentController::class, 'mod'])->name('modstudent');

Route::middleware(['auth:sanctum', 'verified'])->get('/student/mod/{id}', [StudentController::class, 'showMod'])->name('showmodstudent');

Route::middleware(['auth:sanctum', 'verified'])->get('/student/{id}/show', [StudentController::class, 'show_details'])->name('showstudent');

Route::middleware(['auth:sanctum', 'verified'])->get('/familly', [FamillyController::class, 'show'])->name('familly');

Route::middleware(['auth:sanctum', 'verified'])->get('/familly/new', [FamillyController::class, 'new'])->name('newfamilly');

Route::middleware(['auth:sanctum', 'verified'])->post('/familly/add', [FamillyController::class, 'add'])->name('addfamilly');

Route::middleware(['auth:sanctum', 'verified'])->get('/familly/del/{id}', [FamillyController::class, 'del'])->name('delfamilly');

Route::middleware(['auth:sanctum', 'verified'])->post('/familly/mod', [FamillyController::class, 'mod'])->name('modfamilly');

Route::middleware(['auth:sanctum', 'verified'])->get('/familly/mod/{id}', [FamillyController::class, 'showMod'])->name('showmodfamilly');

Route::middleware(['auth:sanctum', 'verified'])->get('/familly/{id}/show', [FamillyController::class, 'show_details'])->name('showfamilly');

Route::middleware(['auth:sanctum', 'verified'])->get('/familly/{id}/student/new', [FamillyController::class, 'new_minor'])->name('newchild');

Route::middleware(['auth:sanctum', 'verified'])->post('/familly/{id}/student/add', [FamillyController::class, 'add_minor'])->name('addchild');

Route::middleware(['auth:sanctum', 'verified'])->get('/minorstudent/attestation_download/', [FamillyController::class, 'download_attestation'])->name('download_attestation');

Route::middleware(['auth:sanctum', 'verified'])->get('/minorstudent/{id}/show', [FamillyController::class, 'show_details_minor_student'])->name('showminorstudent');

Route::middleware(['auth:sanctum', 'verified'])->get('/minorstudent/{id}/showonly', [FamillyController::class, 'show_details_only_minor_student'])->name('showonlyminorstudent');

Route::middleware(['auth:sanctum', 'verified'])->get('/minorstudent/del/{id}', [FamillyController::class, 'del_minor'])->name('del_minorstudent');

Route::middleware(['auth:sanctum', 'verified'])->post('/minorstudent/mod', [FamillyController::class, 'mod_minorstudent'])->name('mod_minorstudent');

Route::middleware(['auth:sanctum', 'verified'])->get('/minorstudent/mod/{id}', [FamillyController::class, 'showmod_minorstudent'])->name('showmod_minorstudent');

Route::middleware(['auth:sanctum', 'verified'])->get('/session', [CourseSessionController::class, 'show'])->name('session');

Route::middleware(['auth:sanctum', 'verified'])->get('/session/new', [CourseSessionController::class, 'new'])->name('newsession');

Route::middleware(['auth:sanctum', 'verified'])->get('/session/fiche', [CourseSessionController::class, 'voir'])->name('fichesession');

Route::middleware(['auth:sanctum', 'verified'])->post('/session/{id}/voir}', [CourseSessionController::class, 'show_ecole'])->name('showInter');

Route::middleware(['auth:sanctum', 'verified'])->post('/session/add', [CourseSessionController::class, 'add'])->name('addsession');

Route::middleware(['auth:sanctum', 'verified'])->get('/session/{id}/show', [CourseSessionController::class, 'show_details'])->name('showsession');

Route::middleware(['auth:sanctum', 'verified'])->get('/session/{id}/mailer', [CourseSessionController::class, 'show_mailers'])->name('showmailers');

Route::middleware(['auth:sanctum', 'verified'])->get('/session/{id}/ficheDeStage', [CourseSessionController::class, 'ficheDeStage'])->name('ficheStage');

Route::middleware(['auth:sanctum', 'verified'])->get('/session/{id}/list', [SessionStudentController::class, 'list'])->name('sessionlist');

Route::middleware(['auth:sanctum', 'verified'])->get('/session/{id}/planning', [CourseSessionController::class, 'show_planning'])->name('showplanning');

Route::middleware(['auth:sanctum', 'verified'])->get('/session/{id}/planning/modify', [CourseSessionController::class, 'modify_planning'])->name('modifyplanning');

Route::middleware(['auth:sanctum', 'verified'])->get('/session/{id}/modify', [CourseSessionController::class, 'modify'])->name('modifysession');

Route::middleware(['auth:sanctum', 'verified'])->post('/session/{id}/modify', [CourseSessionController::class, 'applyModify'])->name('modifysession');

Route::middleware(['auth:sanctum', 'verified'])->post('/session/{id}/publish', [CourseSessionController::class, 'publish'])->name('publishsession');

Route::middleware(['auth:sanctum', 'verified'])->post('/session/{id}/halt', [CourseSessionController::class, 'halt'])->name('haltsession');

Route::middleware(['auth:sanctum', 'verified'])->post('/api/deletelesson', [CourseSessionController::class, 'deleteLesson'])->name('deletelesson');

Route::middleware(['auth:sanctum', 'verified'])->get('/sessionstudent/{id}', [SessionStudentController::class, 'detail'])->name('sessionstudent');

Route::middleware(['auth:sanctum', 'verified'])->get('/contributor', [ContributorController::class, 'show'])->name('contributor');

Route::middleware(['auth:sanctum', 'verified'])->get('/contributor/new', [ContributorController::class, 'new'])->name('newcontributor');

Route::middleware(['auth:sanctum', 'verified'])->post('/contributor/add', [ContributorController::class, 'add'])->name('addcontributor');

Route::middleware(['auth:sanctum', 'verified'])->get('/contributor/del/{id}', [ContributorController::class, 'del'])->name('delcontributor');

Route::middleware(['auth:sanctum', 'verified'])->get('/contributor/{id}/show', [ContributorController::class, 'show_details'])->name('showcontributor');

Route::middleware(['auth:sanctum', 'verified'])->get('/contributor/{id}/show_horaire', [ContributorController::class, 'show_horaire'])->name('ficheHoraire');

Route::middleware(['auth:sanctum', 'verified'])->get('/contributor/{id}/mod', [ContributorController::class, 'showMod'])->name('modcontributor');

Route::middleware(['auth:sanctum', 'verified'])->post('/contributor/{id}/mod', [ContributorController::class, 'mod'])->name('applymodcontributor');

Route::middleware(['auth:sanctum', 'verified'])->get('/school', [SchoolController::class, 'show'])->name('school');

Route::middleware(['auth:sanctum', 'verified'])->get('/school/new', [SchoolController::class, 'new'])->name('newschool');

Route::middleware(['auth:sanctum', 'verified'])->post('/subject/school', [SchoolController::class, 'add'])->name('addschool');

Route::middleware(['auth:sanctum', 'verified'])->get('/school/del/{id}', [SchoolController::class, 'del'])->name('delschool');

Route::middleware(['auth:sanctum', 'verified'])->get('/school/mod/{id}', [SchoolController::class, 'showMod'])->name('showmodschool');

Route::middleware(['auth:sanctum', 'verified'])->post('/school/mod', [SchoolController::class, 'mod'])->name('modschool');

Route::middleware(['auth:sanctum', 'verified'])->get('/subject', [SubjectController::class, 'show'])->name('subject');

Route::middleware(['auth:sanctum', 'verified'])->get('/subject/new', [SubjectController::class, 'new'])->name('newsubject');

Route::middleware(['auth:sanctum', 'verified'])->post('/subject/add', [SubjectController::class, 'add'])->name('addsubject');

Route::middleware(['auth:sanctum', 'verified'])->get('/subject/del/{id}', [SubjectController::class, 'del'])->name('delsubject');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/appel.blade.php
<x-app-layout>
    <x-slot name="header">
        <x-jet-dropdown>
          <x-slot name="trigger">   
            <button class="flex items-center hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
              <img src="https://img.icons8.com/color/44/000000/book-and-pencil.png"/>
                                <style>
                              img {
                                margin-right: 10px;
                                  position: sticky  ;
                                  margin-bottom: 5px;
                              }
                                </style>
              <div>Appel</div>
              <div class="ml-1">
                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </div>
            </button>
          </x-slot>
          <x-slot name="content">
              <x-jet-dropdown-link href="{{ route('newappel') }}" class="bg-gray-150">
                  Effectuer un appel
              </x-jet-dropdown-link>
              <div class="border-t border-gray-100 "></div>
          </x-slot>
        </x-jet-dropdown>
    </x-slot>
    <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
          <div class="flex flex-col">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                  <table class="min-w-full divide-y divide-red-200">
                    <thead>
                      <tr>
                        <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Créée par
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Date (Jour/Mois/Année/Heure)
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-50">
                          <span class="sr-only">Edit</span>
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-50 d-flex justify-content-end ">
                          <span class="badge badge-secondary display-4 d-flex justify-content-end">Liste des appels effectuées</span>
                        </th>
                      </tr>
                    </thead>
                   <tbody class="bg-white divide-y divide-gray-200">
                     @foreach ($appels as $appel)
                      <tr>
                        <td class="px-6 py-4 whitespace-nowrap">                
                              <div class="text-sm font-medium text-gray-900">
                                {{ $appel->createur }}
                              </div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                            <div class="text-sm font-medium text-gray-900">
                              <span class="border text-blue-800">      
                                  {{ $appel->created_at->format('d.m.Y H:i:s') }}
                              </span>
                            </div>
                        </td>                         
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium bg-white-50">
                        
                           <button name="{{ $appel->id }}" class="text-red-600 hover:text-red-900 delete-button" data-toggle="modal" data-target="#confirmDeleteModal">Supprimer</button>
                            <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium bg-blue-50">
                             <a href="{{ route('list_appel', ['id'=>$appel->id])}}" class="text-indigo-600 hover:text-indigo-900">Voir</a>
                            </td>
                        </td>
                      </tr>
                     @endforeach
                    </tbody> 
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal pour confirmer la supression d'un appel -->
    <div class="modal fade" id="confirmDeleteModal" data-selected-subject="0" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header bg-red-600 ">
            <h5 class="modal-title text-light" id="confirmDeleteModalTitle">Confirmation</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Êtes-vous sur de vouloir supprimer cette appel ? </br>
            Vous supprimerez toutes les informations concernant la présence des élèves à la date inscrite !
          </div>   
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
            <button id="confirmDelete" type="button" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">Supprimer</button>
          </div>
        </div>
      </div>
    </div>
    <script type="text/javascript">
        $(".delete-button").click(function(){
            $("#confirmDeleteModal").attr("data-selected-subject",this.name)
        })
        $("#confirmDelete").click(function(){
            $(location).attr("href", "/appel/del/"+$("#confirmDeleteModal").attr('data-selected-subject'));
        })
    </script>       
</x-app-layout>

resources/views/coursesession.blade.php
<x-app-layout>
    <x-slot name="header">
        <x-jet-dropdown>
          <x-slot name="trigger">
            <button class="flex items-center hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
              <img src="https://img.icons8.com/external-others-phat-plus/40/000000/external-entertainment-studio-color-line-others-phat-plus-5.png"/>
                      <style>
                      img {
                        margin-right: 13px;
                          position: sticky  ;
                          margin-bottom: 5px;
                      }
                      </style>
              <div>Stages</div>
              <div class="ml-1">
                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </div>
            </button>
          </x-slot>
          <x-slot name="content">
              <x-jet-dropdown-link href="{{ route('newsession') }}" class="bg-gray-100">
                  Ajouter un stage
              </x-jet-dropdown-link>
              <div class="border-t border-gray-100 "></div>
          </x-slot>
        </x-jet-dropdown>
    </x-slot>
    <div class="py-12">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
          <div class="flex flex-col">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                  <table class="min-w-full divide-y divide-gray-200">
                    <thead>
                      <tr>
                        <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Date Début
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Date Fin
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Nombre d'inscrit
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          État
                        </th>
                        <th scope="col" class="px-6 py-3 bg-gray-50">
                          <span class="sr-only">Edit</span>
                        </th>
                      </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                      @foreach ($courseSessions as $courseSession)
                      <tr>
                        <td class="px-6 py-4 whitespace-nowrap">
                          <div class="flex items-center">
                            <div class="ml-4">
                              <div class="text-sm font-medium text-gray-900">
                                {{date('d/m/Y', strtotime($courseSession->starting))}}
                              </div>
                            </div>
                          </div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                          <div class="text-sm text-gray-900">
                            {{date('d/m/Y', strtotime($courseSession->endding))}}  
                          </div>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                        @if ($courseSession->lessons()->count()*$courseSession->places != 0 && $courseSession->students()->count() == $courseSession->lessons()->count()*$courseSession->places)
                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-200 text-green-800">
                          {{ $courseSession->students()->count() }} - Complet
                        </span>
                        @else
                        <span class="px-2 inline-flex text-xs leading-5 font-semibold text-gray-800">
                          {{ $courseSession->students()->count() }}
                        </span>
                        @endif
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap">
                          @if (Carbon::createFromFormat('Y-m-d',$courseSession->endding)->gt(Carbon::createFromFormat('Y-m-d',date('Y-m-d'))))
                              @if ($courseSession->published)
                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-200 text-green-800">
                                  Publié
                                </span>
                              @else
                                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-200 text-red-800">
                                  Brouillon
                                </span>
                              @endif
                          @else
                            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-200 text-gray-800">
                              Terminé
                            </span>
                          @endif  
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right text-xl font-medium">
                          <a href="{{ route('showmailers',['id'=>$courseSession->id]) }}" class="text-indigo-600 hover:text-indigo-900">
                            <i class="fa fa-envelope" aria-hidden="true"></i></a>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          <a href="{{ route('showsession',['id'=>$courseSession->id]) }}" class="text-indigo-600 hover:text-indigo-900">Voir les informations</a>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          <a href="{{ route('showplanning',['id'=>$courseSession->id]) }}" class="text-indigo-600 hover:text-indigo-900">Voir le planning</a>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          <a href="{{ route('ficheStage',['id'=>$courseSession->id]) }}" class="text-indigo-600 hover:text-indigo-900" >Fiche horaire stage</a>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">            
                          <a href="{{ route('attendance',['id'=>$courseSession->id]) }}" class="text-indigo-600 hover:text-indigo-900">Appel</a>
                        </td>

                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                          @if (Carbon::createFromFormat('Y-m-d',$courseSession->endding)->gt(Carbon::createFromFormat('Y-m-d',date('Y-m-d'))))
                              @if ($courseSession->published)
                                <form action="{{ route('haltsession',['id'=>$courseSession->id]) }}" method="post">
                                  @csrf
                                  <button type="submit" class="btn btn-warning">Suspendre</button></a>
                                </form>
                              @else
                                <form action="{{ route('publishsession',['id'=>$courseSession->id]) }}" method="post">
                                  @csrf
                                  <button type="submit" class="btn btn-primary">Publier</button></a>
                                </form>
                              @endif
                          @else
                            @if ($courseSession->published)
                              <button type="submit" class="btn btn-secondary" disabled>Suspendre</button></a>
                            @else
                              <button type="submit" class="btn btn-secondary" disabled>Publier</button></a>
                            @endif
                          @endif  
 
                        </td>
                      </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
    </div>
</x-app-layout>

resources/views/famillydetails.blade.php
<x-app-layout>
  <x-slot name="header">
    <h2 class="leading-tight text-base">
      <a href="{{ route('familly') }}" class="text-blue-700">Famille </a>/ Information de la famille <i>({{ $familly->first_name }} {{ $familly->last_name }})</i>
    </h2>
  </x-slot>
  <div class="py-12">
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
      <div class="bg-white shadow overflow-hidden sm:rounded-lg">
        <div class="px-4 py-5 sm:px-6 flex object-right justify-between bg-gray-50">
          <h3 class="text-lg leading-6 font-medium text-gray-900">
            Détails de la famille
          </h3>
          <span class="sm:ml-3">
            <a href="/familly/mod/{{ $familly->id }}">
              <button type="button" class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Modifier
              </button>
            </a>
          </span>
        </div>
        <div class="border-t border-gray-200">
          <dl>
            <div class="bg-white-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">
                Nom, Prénom
              </dt>
              <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                {{ $familly->last_name }}   {{ $familly->first_name }}
              </dd>
            </div>        
            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">
                Email
              </dt>
              <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                {{ $familly->email_address }}
              </dd>
            </div>
            <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">
                Téléphone
              </dt>
              <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                {{ $familly->phone_number }}
              </dd>
            </div>
            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">
                Adresse
              </dt>
              <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                {{ $familly->street_address }} </br> {{ $familly->postal_code }}    {{ $familly->city }}
              </dd>
            </div>           
            <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">
                Règlement signé
              </dt>
              <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                @if ($familly->rules===1)
                     <span style="color:red;">Oui</span>
                @else
                    Non
                @endif
              </dd>
            </div>
            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
              <dt class="text-sm font-medium text-gray-500">
                Absence
              </dt>
              <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                @if ($familly->absence===1)
                     <span style="color:red;">Oui</span>
                @else
                    Non
                @endif
              </dd>
            </div>
          </div>
        </dl>
      </div>
    </div>
  </div>
</div>
</x-app-layout>